In [0]:
import torch

In [0]:
def activation(x):
  return 1/(1+torch.exp(-x))

In [0]:
torch.manual_seed(7)

features = torch.randn((1, 5))
weights = torch.rand_like(features)

bias = torch.randn((1, 1))

In [12]:
torch.matmul(features, weights.view(5, 1))

tensor([[1.3592]])

In [0]:
torch.manual_seed(7)

features = torch.randn((1, 3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))




In [32]:
z = torch.add(torch.matmul(features, W1), b1)
a = activation(z)
o = torch.add(torch.matmul(a, W2), b2)
o = activation(o)
o

tensor([[0.3171]])

In [0]:
import numpy as np

In [35]:
a = np.random.rand(4, 3)
a

array([[0.80699185, 0.31767882, 0.64695696],
       [0.19461783, 0.75210534, 0.10054803],
       [0.65637573, 0.14584952, 0.37685669],
       [0.06622911, 0.12107514, 0.97041293]])

In [36]:
b = torch.from_numpy(a)
b

tensor([[0.8070, 0.3177, 0.6470],
        [0.1946, 0.7521, 0.1005],
        [0.6564, 0.1458, 0.3769],
        [0.0662, 0.1211, 0.9704]], dtype=torch.float64)

In [37]:
b.numpy()

array([[0.80699185, 0.31767882, 0.64695696],
       [0.19461783, 0.75210534, 0.10054803],
       [0.65637573, 0.14584952, 0.37685669],
       [0.06622911, 0.12107514, 0.97041293]])

In [38]:
b.mul_(2)

tensor([[1.6140, 0.6354, 1.2939],
        [0.3892, 1.5042, 0.2011],
        [1.3128, 0.2917, 0.7537],
        [0.1325, 0.2422, 1.9408]], dtype=torch.float64)

In [39]:
a

array([[1.6139837 , 0.63535764, 1.29391391],
       [0.38923566, 1.50421068, 0.20109606],
       [1.31275146, 0.29169905, 0.75371338],
       [0.13245822, 0.24215028, 1.94082587]])